services:
  ####################### APPLICATION #######################
  app:
    container_name: node-pipeline-local
    build:
      context: ../..
      dockerfile: deploy/dev/Dockerfile
      #    environment:
      # - PORT=${APP_PORT}
#    env_file: .env
    ports:
      - 3000:3000
#      - "${APP_PORT}:${APP_PORT}"
    volumes:
#      - ./:/app
      - ../../:/app
