services:
  ####################### APPLICATION #######################
  node-pipeline-local-dev:
    container_name: node-pipeline-local-dev
    build:
      context: ../..
      dockerfile: deploy/dev/Dockerfile
#    env_file:
#      - .env
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ../../:/app
    profiles:
      - dev
